CREATE TABLE IF NOT EXISTS respondent_record(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time_stamp TEXT,
    age INTEGER NOT NULL,
    gender TEXT NOT NULL,
    country TEXT NOT NULL,
    state_ TEXT,
    self_employed TEXT,
    family_history TEXT,
    treatment TEXT NOT NULL,
    work_interference_level TEXT,
    no_employees TEXT NOT NULL,
    remote_work TEXT NOT NULL,
    tech_company TEXT,
    benefits TEXT NOT NULL,
    care_options TEXT NOT NULL,
    wellness_program TEXT,
    seek_help TEXT,
    anonymity TEXT,
    leave TEXT,
    mental_health_consequence TEXT,
    physical_health_consequence TEXT,
    coworkers TEXT,
    supervisor TEXT,
    mental_health_interview TEXT,
    phys_health_interview TEXT,
    mental_vs_physical TEXT,
    obs_consequence TEXT,
    comments TEXT,

    CONSTRAINT chk_valid_age CHECK (age >= 18 AND age <= 100)

);